Rewrite: Initial structure
JJTech0130/pypush pull request #100
Opened 2024-05-11 16:06 UTC by JJTech0130

Trying to get the ball rolling here, this is my proposal for an initial structure of the rewrite.

I've structured it so that APNs will eventually be published as it's own independent PyPI package.

Still need:
+ [ ] Rewrite actual APNs implementation, using `asyncio` this time
+ [ ] Work out API for device details and versions

2024-05-11 16:11 UTC, JJTech0130 commented
Maybe this time I should go ahead and implement https://github.com/JJTech0130/pypush/issues/61 right off the bat

2024-05-11 20:46 UTC, JJTech0130 commented
Here's how the package structure and API is looking:

`pypush-apns` and `pypush` are the package names for now. Might need to be renamed if I can't get `pypush` on pypi
`pypush` depends on `pypush-apns`, but APNs can be used independently 

The namespace means you can use it like this:
```py
import pypush.apns
```
no matter how you install it

2024-05-13 01:36 UTC, JJTech0130 commented
Using `asyncio` over `trio` for the added API flexibility, though it does bring some additional pitfalls and possible footguns...

Can now provide 2 APIs:
```py
@pytest.mark.asyncio
async def test_connect():
    connection = apns.connection.Connection(certificate, key)
    await connection.connect()
    assert connection.connected == True
    await connection.aclose()
    assert connection.connected == False
```
and
```py
@pytest.mark.asyncio
async def test_with_block():
    async with apns.connection.Connection(certificate, key) as connection:
        assert connection.connected == True
    assert connection.connected == False
```

I store both the event loop and a list of tasks to cancel inside `Connection`, I'm not sure if that is the best way to use asyncio?

2024-05-13 18:01 UTC, doronz88 requested changes

2024-05-13 18:01 UTC, doronz88 commented on README.md
> +1. `git clone https://github.com/JJTech0130/pypush.git`
should be written in a singular code block so people can just copy-paste it to terminal

2024-05-13 18:01 UTC, doronz88 commented on README.md
> +3. `pip install -e ./apns`
making it a different package makes it quite confusing. i think it should either be a git submodule or just a just another module within pypush

2024-05-13 18:01 UTC, doronz88 commented on apns/pyproject.toml
> +version = "0.0.1"
not really necessary - but i recommend using setuptools-scm

2024-05-13 19:14 UTC, JJTech0130 commented
Honestly probably going to stick with recommending
`pip install git+https://github.com/JJTech0130/pypush`
rather than deal with publishing to PyPi for now

(`pip install git+https://github.com/JJTech0130/pypush@initial-rewrite-structure` for this branch)

2024-05-13 19:27 UTC, doronz88 commented on pyproject.toml
> +
```suggestion
version_file = "pypush/_version.py"
```
Also, don't forget to add this into gitignore file

2024-05-15 12:37 UTC, BuyAppleidinbulk commented
@JJTech0130   Please contact me

2024-05-15 15:05 UTC, JJTech0130 commented
`apnsproxy` is now working: it allows you to see the APNs packets that your local machine is sending over the wire. Note that it requires SIP to be disabled.

```sh
python3.11 -m venv venv
source ./venv/bin/activate

pip install 'pypush[proxy] @ git+https://github.com/JJTech0130/pypush@initial-rewrite-structure'
sudo apnsproxy
```

2024-05-16 14:39 UTC, JJTech0130 commented
Just refactored the CLI, the command is now just `pypush`, `pypush proxy` replaces the `apnsproxy` command.

2024-05-18 00:02 UTC, AngeloD2022 commented on pypush/apns/lifecycle.py
> +            assert ack.status == 0
Might be worth implementing custom exceptions to differentiate between problems that might occur, and potentially actuate different resilience strategies.

2024-05-18 00:02 UTC, AngeloD2022 commented on pypush/apns/protocol.py
> +@dataclass
Since every class decorated by `auto_packet` is also a `dataclass`, can we potentially consolidate the two decorators by applying the `dataclass` decorator within the `auto_packet` implementation?

2024-05-18 00:02 UTC, AngeloD2022 commented on pypush/apns/_protocol.py
> +def auto_packet(cls: T) -> T:
Just a small thing– but it might be more intuitive to rename this to `@command` or `@apns_command`

2024-05-18 00:02 UTC, AngeloD2022 commented on pypush/apns/_protocol.py
> +            field_value = packet.fields_for_id(f.metadata["packet_id"])
Use `get_args` and `get_origin` from the `typing` package instead of parsing the type string.

2024-05-18 01:00 UTC, JJTech0130 commented on pypush/apns/lifecycle.py
> +            assert ack.status == 0
My strategy right now has pretty much been "if something goes wrong, catch it with `except Exception as e` and try again... perhaps some proper exceptions can go in the next PR

2024-05-18 01:26 UTC, JJTech0130 commented on pypush/apns/protocol.py
> +@dataclass
this is actually harder than it sounds, I tried it and it messed up type checking...

2024-05-18 01:48 UTC, merged